import { EvidenceBadge, type EvidenceDisplayLabel } from '../components/evidence/EvidenceBadge'
import { EvidenceBubbleGraphic } from '../components/evidence/EvidenceBubbleGraphic'
import { ResearchFilters } from '../components/evidence/ResearchFilters'
import { PageContainer } from '../components/PageContainer'
import { PageMeta } from '../components/PageMeta'
import { SectionHeading } from '../components/SectionHeading'
import { researchSources, type ResearchCategory } from '../data/research'

const legend: { label: EvidenceDisplayLabel; description: string }[] = [
  { label: 'Stronger evidence', description: 'Used for systematic reviews, meta-analyses, and reviews of randomized trials.' },
  { label: 'Emerging evidence', description: 'Used for observational, exploratory, or early Carnatic-specific research.' },
  { label: 'Background context', description: 'Used for neuroscience reviews, musicology, and historical reference material.' },
]

const evidenceSummaries: { title: string; copy: string; label: EvidenceDisplayLabel }[] = [
  { title: 'Mood and depressive symptoms', copy: 'Across multiple systematic reviews and meta-analyses, music-based interventions were associated with reductions in depressive symptoms and improvements in emotional well-being among people with dementia. Depression is one of the outcomes with the most consistent support, although effects differ by program, setting, and participant.', label: 'Most consistent evidence' },
  { title: 'Cognition', copy: 'Several reviews report short-term cognitive improvements, particularly in programs involving active participation such as singing, rhythm, or music-making. However, relatively few randomized studies are available, and evidence about lasting benefits remains limited.', label: 'Promising evidence' },
  { title: 'Behavior and quality of life', copy: 'Some reviews report improvements in agitation, behavioral symptoms, engagement, or quality of life. Results are not consistent across all analyses, suggesting that intervention design, personalization, and care setting may influence outcomes.', label: 'Mixed evidence' },
  { title: 'Carnatic music and aging', copy: 'Early observational research has examined long-term Carnatic musical activity in relation to cognitive functioning during aging. These findings support further investigation, but they do not show that Carnatic music prevents cognitive decline or treats dementia.', label: 'Emerging evidence' },
]

const researchGaps = [
  'Whether Carnatic music produces different outcomes from other musical traditions',
  'Whether culturally familiar music improves response',
  'Which ragas, musical features, or participation styles matter most',
  'The best duration and frequency for interventions',
  'Whether benefits persist over time',
  'Whether findings differ by dementia type or stage',
  'How active participation compares with passive listening',
  'How caregiver involvement changes outcomes',
]

const takeaways = [
  'Multiple reviews support music-based interventions for depressive symptoms and emotional well-being in dementia care.',
  'Cognitive benefits have been reported, particularly with active participation, but the evidence base remains relatively small.',
  'Results for agitation, behavior, and quality of life differ across reviews and settings.',
  'Personalization, cultural familiarity, active engagement, intervention intensity, and care context may influence outcomes.',
  'Neuroscience provides plausible explanations for music’s effects on attention, emotion, memory, movement, and reward, but mechanisms do not prove clinical effectiveness.',
  'Carnatic-specific evidence is emerging and does not yet support treatment or prevention claims.',
]

function ThemeSources({ category }: { category: ResearchCategory }) {
  const sources = researchSources.filter((source) => source.category === category)
  return <div className="mt-8"><h4 className="font-display text-xl font-bold">Research in this theme</h4><ul className="mt-4 grid gap-3 md:grid-cols-2">{sources.map((source) => <li className="rounded-xl border border-teal-900/15 bg-white/55 p-4" key={source.id}><p className="font-semibold leading-6">{source.citation}</p><p className="mt-2 text-sm text-teal-700">{source.evidenceLevel} · {source.evidenceLabel}</p></li>)}</ul></div>
}

export function Evidence() {
  return <>
    <PageMeta title="Evidence Hub" description="Explore research on music, the brain, dementia, and Carnatic musical traditions with clear limitations and evidence labels." />

    <header className="border-b border-teal-900/10 py-16 sm:py-24">
      <PageContainer className="grid items-center gap-12 lg:grid-cols-[1.15fr_.85fr] lg:gap-16">
        <div><p className="text-sm font-bold uppercase tracking-[.22em] text-gold-700">Research, translated carefully</p><h1 className="mt-5 font-display text-5xl font-bold leading-tight sm:text-7xl">Evidence Hub</h1><p className="mt-7 max-w-3xl text-xl leading-8 text-teal-800">Explore what current research says about music, the brain, dementia, and Carnatic musical traditions. RagaMind presents evidence with its limitations so readers can distinguish promising findings from unanswered questions.</p><p className="mt-6 max-w-3xl border-l-2 border-gold-700 pl-4 leading-7 text-teal-700">This page is educational and is not a substitute for medical advice, diagnosis, or treatment.</p></div>
        <EvidenceBubbleGraphic />
      </PageContainer>
    </header>

    <section className="py-16 sm:py-20" aria-labelledby="evidence-legend-title"><PageContainer><h2 className="font-display text-3xl font-bold" id="evidence-legend-title">How evidence is labeled</h2><div className="mt-8 grid gap-5 md:grid-cols-3">{legend.map((item) => <article className="rounded-2xl border border-teal-900/15 bg-white/55 p-6" key={item.label}><EvidenceBadge label={item.label} /><p className="mt-4 leading-7 text-teal-800">{item.description}</p></article>)}</div></PageContainer></section>

    <section className="border-y border-teal-900/10 bg-sage-100/60 py-20 sm:py-24"><PageContainer><SectionHeading title="Evidence at a Glance" subtitle="A concise orientation to areas of relative strength and uncertainty." /><div className="mt-10 grid gap-5 md:grid-cols-2">{evidenceSummaries.map((item) => <article className="rounded-2xl border border-teal-900/15 bg-ivory p-6" key={item.title}><EvidenceBadge label={item.label} /><h3 className="mt-5 font-display text-2xl font-bold">{item.title}</h3><p className="mt-4 leading-7 text-teal-800">{item.copy}</p></article>)}</div></PageContainer></section>

    <section className="py-20 sm:py-24"><PageContainer><SectionHeading title="Research Themes" subtitle="Scientific reviews, neuroscience context, and cultural knowledge answer different kinds of questions." /><div className="mt-12 space-y-16">
      <article><h3 className="font-display text-3xl font-bold">Music Therapy and Dementia</h3><p className="mt-4 max-w-4xl leading-7 text-teal-800">Reviews involving people with dementia suggest that structured music interventions may support depressive symptoms, mood, emotional well-being, engagement, and selected behavioral outcomes.</p><div className="mt-8 grid gap-8 lg:grid-cols-2"><div><h4 className="font-display text-xl font-bold">What we know</h4><div className="mt-4 space-y-4 leading-7 text-teal-800"><p>Some studies report cognitive improvement, especially when participants actively sing, keep rhythm, play instruments, or otherwise make music.</p><p>Individualized and person-centered programs may be more meaningful because musical preference, cultural familiarity, memory, and ability differ among participants. Music therapy delivered by a trained professional is not identical to simply playing recorded music.</p><p>A 2025 meta-analysis reported stronger outcomes in programs lasting at least twelve weeks, involving at least sixteen sessions and approximately eight total hours. This is a finding from that analysis, not a universal prescription. The same analysis did not find significant overall improvements in behavior or quality of life, showing that benefits are not uniform across outcomes.</p></div></div><div><h4 className="font-display text-xl font-bold">What we are still learning</h4><ul className="mt-4 list-disc space-y-3 pl-5 text-teal-800"><li>Which intervention type works best</li><li>Optimal session length and frequency</li><li>Whether benefits last after programs end</li><li>Which outcomes improve consistently</li><li>Which individuals benefit most</li></ul></div></div><p className="mt-8 max-w-5xl rounded-2xl bg-sage-100 p-6 text-lg font-semibold leading-8 text-teal-900">Taken together, the research supports music-based interventions most clearly as a way to assist emotional well-being and participation. Evidence for cognition, behavior, and lasting change is promising but less consistent.</p><ThemeSources category="Music Therapy & Dementia" /></article>
      <article className="border-t border-teal-900/15 pt-14"><h3 className="font-display text-3xl font-bold">Music and the Brain</h3><div className="mt-4 max-w-4xl space-y-4 leading-7 text-teal-800"><p>Music involves coordinated activity across systems related to auditory processing, movement and timing, attention, memory, emotion, prediction, reward, and motivation.</p><p><strong>Neuroplasticity</strong> is the brain’s ability to reorganize and adapt through experience. Musical activity can repeatedly engage networks involved in listening, movement, memory, language, and emotion.</p><p>This biological plausibility helps explain why music is studied in rehabilitation and dementia care. It does not, by itself, prove that a particular musical activity produces a clinical benefit.</p></div><div className="mt-8 max-w-4xl rounded-2xl bg-sage-100 p-6"><h4 className="font-display text-xl font-bold">Why active participation may matter</h4><p className="mt-3 leading-7 text-teal-800">Listening engages auditory, emotional, and predictive systems. Singing, keeping rhythm, or making music may additionally involve movement, attention, memory, language, and social interaction. This may help explain why some studies report stronger results for active participation than passive listening.</p></div><ThemeSources category="Music & Neuroscience" /></article>
      <article className="border-t border-teal-900/15 pt-14"><h3 className="font-display text-3xl font-bold">Carnatic Music, Emotion, and Aging</h3><div className="mt-4 max-w-4xl space-y-4 leading-7 text-teal-800"><p>Carnatic music is a highly developed South Indian classical tradition shaped by raga, rhythm, composition, improvisation, devotion, and centuries of teaching. Traditional associations between ragas, emotion, time, and aesthetic experience form an important body of cultural knowledge.</p><p>Scientific research on Carnatic music remains much smaller than the broader literature on music and health. Exploratory studies have attempted to model emotional responses to ragas, while observational research has examined long-term Carnatic musical activity and cognitive functioning in older adults. These studies raise meaningful questions, but they do not yet establish clinical effectiveness.</p></div><div className="mt-8 grid gap-5 lg:grid-cols-2"><article className="rounded-2xl border border-gold-700/35 bg-sage-100 p-6"><h4 className="font-display text-xl font-bold">Traditional knowledge</h4><ul className="mt-4 list-disc space-y-3 pl-5 text-teal-800"><li>Developed through long-term musical practice, teaching, performance, and cultural experience</li><li>Valuable for understanding how musicians and listeners experience ragas</li><li>Should be identified as cultural or experiential knowledge</li></ul></article><article className="rounded-2xl border border-teal-900/15 bg-white/60 p-6"><h4 className="font-display text-xl font-bold">Scientific evidence</h4><ul className="mt-4 list-disc space-y-3 pl-5 text-teal-800"><li>Developed through defined research methods and measurable outcomes</li><li>Evaluated through study design, replication, sample size, and limitations</li><li>Required before making clinical or treatment claims</li></ul></article></div><p className="mt-5 max-w-4xl text-sm leading-6 text-teal-700">Neither category is meaningless. They answer different kinds of questions and should be identified clearly.</p><ThemeSources category="Carnatic Music & Musicology" /></article>
    </div></PageContainer></section>

    <section className="border-y border-teal-900/10 bg-white/35 py-20 sm:py-24"><PageContainer><SectionHeading title="What Researchers Still Do Not Know" subtitle="These questions mark important limits in the current evidence." /><ul className="mt-10 grid gap-4 md:grid-cols-2">{researchGaps.map((item) => <li className="border-l-2 border-gold-700 py-2 pl-4 text-lg leading-7 text-teal-800" key={item}>{item}</li>)}</ul></PageContainer></section>

    <section className="py-20 sm:py-24"><PageContainer><SectionHeading title="How Strong Is the Evidence?" subtitle="Different source types contribute different levels of confidence and context." /><div className="mt-10 grid gap-5 lg:grid-cols-3"><article className="rounded-2xl border border-teal-900/15 bg-white/60 p-6"><h3 className="font-display text-xl font-bold">Higher-level evidence used on this site</h3><p className="mt-4 leading-7 text-teal-800">Systematic reviews, meta-analyses, and reviews of randomized controlled trials combine findings from multiple studies. Their conclusions are only as strong as the studies included.</p></article><article className="rounded-2xl border border-teal-900/15 bg-white/60 p-6"><h3 className="font-display text-xl font-bold">Individual and observational evidence</h3><p className="mt-4 leading-7 text-teal-800">Randomized controlled trials, observational studies, and exploratory studies can provide useful findings but may be limited by sample size, study design, participant differences, or the absence of comparison groups.</p></article><article className="rounded-2xl border border-teal-900/15 bg-white/60 p-6"><h3 className="font-display text-xl font-bold">Background and theoretical evidence</h3><p className="mt-4 leading-7 text-teal-800">Neuroscience reviews, historical sources, and musicology references help explain mechanisms and cultural context but do not establish that an intervention is clinically effective.</p></article></div><p className="mt-8 max-w-5xl rounded-2xl bg-sage-100 p-6 font-semibold leading-7 text-teal-900">A review can still produce uncertain conclusions when the included studies use very different interventions, populations, or outcome measures.</p></PageContainer></section>

    <section className="border-t border-teal-900/10 bg-white/35 py-20 sm:py-24"><PageContainer><SectionHeading title="Research Library" subtitle="Filter all 14 supplied sources by category or evidence label. Each collapsed card shows its key finding; open it for the summary, limitations, relevance, and interpretation guidance." /><div className="mt-10"><ResearchFilters sources={researchSources} /></div></PageContainer></section>

    <section className="bg-sage-100/60 py-20 sm:py-24"><PageContainer><SectionHeading title="Key Takeaways" /><ol className="mt-8 grid gap-4 lg:grid-cols-2">{takeaways.map((item, index) => <li className="flex gap-4 rounded-xl bg-ivory p-5 leading-7 text-teal-800" key={item}><span className="font-display text-xl font-bold text-gold-700">{index + 1}</span><span>{item}</span></li>)}</ol></PageContainer></section>

    <section className="bg-teal-950 py-12 text-white" aria-labelledby="final-disclaimer-title"><PageContainer><h2 className="font-display text-2xl font-bold" id="final-disclaimer-title">Educational disclaimer</h2><p className="mt-4 max-w-5xl text-lg leading-8">RagaMind is an educational project. It does not provide medical advice and does not recommend replacing clinical care with music-based activities.</p></PageContainer></section>
  </>
}
